# Real hardware controller_manager config. This uses main_bot_hardware/RealSystem
# over /joint_cmd, /joint_fb and /joint_diag through micro-ROS/UART.
controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    megadog_controller:
      type: megadog_controller/MegadogController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE
    interfaces:
      - visual_position
      - visual_velocity
      - effort
    map_interface_to_joint_state:
      position: visual_position
      velocity: visual_velocity
